# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from frontier_exploration/Frontier.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Frontier(genpy.Message):
  _md5sum = "8e57df42619e81a60a4a5920d716e4b4"
  _type = "frontier_exploration/Frontier"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 size
float64 min_distance
geometry_msgs/Point travel_point

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['size','min_distance','travel_point']
  _slot_types = ['uint32','float64','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       size,min_distance,travel_point

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Frontier, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.size is None:
        self.size = 0
      if self.min_distance is None:
        self.min_distance = 0.
      if self.travel_point is None:
        self.travel_point = geometry_msgs.msg.Point()
    else:
      self.size = 0
      self.min_distance = 0.
      self.travel_point = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_I4d().pack(_x.size, _x.min_distance, _x.travel_point.x, _x.travel_point.y, _x.travel_point.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.travel_point is None:
        self.travel_point = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.size, _x.min_distance, _x.travel_point.x, _x.travel_point.y, _x.travel_point.z,) = _get_struct_I4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_I4d().pack(_x.size, _x.min_distance, _x.travel_point.x, _x.travel_point.y, _x.travel_point.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.travel_point is None:
        self.travel_point = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.size, _x.min_distance, _x.travel_point.x, _x.travel_point.y, _x.travel_point.z,) = _get_struct_I4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_I4d = None
def _get_struct_I4d():
    global _struct_I4d
    if _struct_I4d is None:
        _struct_I4d = struct.Struct("<I4d")
    return _struct_I4d
