// Generated by gencpp from file astra_camera/GetDeviceType.msg
// DO NOT EDIT!


#ifndef ASTRA_CAMERA_MESSAGE_GETDEVICETYPE_H
#define ASTRA_CAMERA_MESSAGE_GETDEVICETYPE_H

#include <ros/service_traits.h>


#include <astra_camera/GetDeviceTypeRequest.h>
#include <astra_camera/GetDeviceTypeResponse.h>


namespace astra_camera
{

struct GetDeviceType
{

typedef GetDeviceTypeRequest Request;
typedef GetDeviceTypeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDeviceType
} // namespace astra_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::astra_camera::GetDeviceType > {
  static const char* value()
  {
    return "4c8e9dd50b39344412b92ce9e1e9615c";
  }

  static const char* value(const ::astra_camera::GetDeviceType&) { return value(); }
};

template<>
struct DataType< ::astra_camera::GetDeviceType > {
  static const char* value()
  {
    return "astra_camera/GetDeviceType";
  }

  static const char* value(const ::astra_camera::GetDeviceType&) { return value(); }
};


// service_traits::MD5Sum< ::astra_camera::GetDeviceTypeRequest> should match
// service_traits::MD5Sum< ::astra_camera::GetDeviceType >
template<>
struct MD5Sum< ::astra_camera::GetDeviceTypeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::GetDeviceType >::value();
  }
  static const char* value(const ::astra_camera::GetDeviceTypeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::GetDeviceTypeRequest> should match
// service_traits::DataType< ::astra_camera::GetDeviceType >
template<>
struct DataType< ::astra_camera::GetDeviceTypeRequest>
{
  static const char* value()
  {
    return DataType< ::astra_camera::GetDeviceType >::value();
  }
  static const char* value(const ::astra_camera::GetDeviceTypeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::astra_camera::GetDeviceTypeResponse> should match
// service_traits::MD5Sum< ::astra_camera::GetDeviceType >
template<>
struct MD5Sum< ::astra_camera::GetDeviceTypeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::GetDeviceType >::value();
  }
  static const char* value(const ::astra_camera::GetDeviceTypeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::GetDeviceTypeResponse> should match
// service_traits::DataType< ::astra_camera::GetDeviceType >
template<>
struct DataType< ::astra_camera::GetDeviceTypeResponse>
{
  static const char* value()
  {
    return DataType< ::astra_camera::GetDeviceType >::value();
  }
  static const char* value(const ::astra_camera::GetDeviceTypeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASTRA_CAMERA_MESSAGE_GETDEVICETYPE_H
