// Generated by gencpp from file astra_camera/GetDeviceTypeResponse.msg
// DO NOT EDIT!


#ifndef ASTRA_CAMERA_MESSAGE_GETDEVICETYPERESPONSE_H
#define ASTRA_CAMERA_MESSAGE_GETDEVICETYPERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace astra_camera
{
template <class ContainerAllocator>
struct GetDeviceTypeResponse_
{
  typedef GetDeviceTypeResponse_<ContainerAllocator> Type;

  GetDeviceTypeResponse_()
    : device_type()  {
    }
  GetDeviceTypeResponse_(const ContainerAllocator& _alloc)
    : device_type(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _device_type_type;
  _device_type_type device_type;





  typedef boost::shared_ptr< ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetDeviceTypeResponse_

typedef ::astra_camera::GetDeviceTypeResponse_<std::allocator<void> > GetDeviceTypeResponse;

typedef boost::shared_ptr< ::astra_camera::GetDeviceTypeResponse > GetDeviceTypeResponsePtr;
typedef boost::shared_ptr< ::astra_camera::GetDeviceTypeResponse const> GetDeviceTypeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator1> & lhs, const ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.device_type == rhs.device_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator1> & lhs, const ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace astra_camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c8e9dd50b39344412b92ce9e1e9615c";
  }

  static const char* value(const ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c8e9dd50b393444ULL;
  static const uint64_t static_value2 = 0x12b92ce9e1e9615cULL;
};

template<class ContainerAllocator>
struct DataType< ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "astra_camera/GetDeviceTypeResponse";
  }

  static const char* value(const ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string device_type\n"
;
  }

  static const char* value(const ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.device_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetDeviceTypeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::astra_camera::GetDeviceTypeResponse_<ContainerAllocator>& v)
  {
    s << indent << "device_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.device_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASTRA_CAMERA_MESSAGE_GETDEVICETYPERESPONSE_H
