// Generated by gencpp from file astra_camera/GetUVCGain.msg
// DO NOT EDIT!


#ifndef ASTRA_CAMERA_MESSAGE_GETUVCGAIN_H
#define ASTRA_CAMERA_MESSAGE_GETUVCGAIN_H

#include <ros/service_traits.h>


#include <astra_camera/GetUVCGainRequest.h>
#include <astra_camera/GetUVCGainResponse.h>


namespace astra_camera
{

struct GetUVCGain
{

typedef GetUVCGainRequest Request;
typedef GetUVCGainResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetUVCGain
} // namespace astra_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::astra_camera::GetUVCGain > {
  static const char* value()
  {
    return "164d2201bda8580473ff7023ba27f703";
  }

  static const char* value(const ::astra_camera::GetUVCGain&) { return value(); }
};

template<>
struct DataType< ::astra_camera::GetUVCGain > {
  static const char* value()
  {
    return "astra_camera/GetUVCGain";
  }

  static const char* value(const ::astra_camera::GetUVCGain&) { return value(); }
};


// service_traits::MD5Sum< ::astra_camera::GetUVCGainRequest> should match
// service_traits::MD5Sum< ::astra_camera::GetUVCGain >
template<>
struct MD5Sum< ::astra_camera::GetUVCGainRequest>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::GetUVCGain >::value();
  }
  static const char* value(const ::astra_camera::GetUVCGainRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::GetUVCGainRequest> should match
// service_traits::DataType< ::astra_camera::GetUVCGain >
template<>
struct DataType< ::astra_camera::GetUVCGainRequest>
{
  static const char* value()
  {
    return DataType< ::astra_camera::GetUVCGain >::value();
  }
  static const char* value(const ::astra_camera::GetUVCGainRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::astra_camera::GetUVCGainResponse> should match
// service_traits::MD5Sum< ::astra_camera::GetUVCGain >
template<>
struct MD5Sum< ::astra_camera::GetUVCGainResponse>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::GetUVCGain >::value();
  }
  static const char* value(const ::astra_camera::GetUVCGainResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::GetUVCGainResponse> should match
// service_traits::DataType< ::astra_camera::GetUVCGain >
template<>
struct DataType< ::astra_camera::GetUVCGainResponse>
{
  static const char* value()
  {
    return DataType< ::astra_camera::GetUVCGain >::value();
  }
  static const char* value(const ::astra_camera::GetUVCGainResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASTRA_CAMERA_MESSAGE_GETUVCGAIN_H
