// Generated by gencpp from file astra_camera/SetLaser.msg
// DO NOT EDIT!


#ifndef ASTRA_CAMERA_MESSAGE_SETLASER_H
#define ASTRA_CAMERA_MESSAGE_SETLASER_H

#include <ros/service_traits.h>


#include <astra_camera/SetLaserRequest.h>
#include <astra_camera/SetLaserResponse.h>


namespace astra_camera
{

struct SetLaser
{

typedef SetLaserRequest Request;
typedef SetLaserResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLaser
} // namespace astra_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::astra_camera::SetLaser > {
  static const char* value()
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const ::astra_camera::SetLaser&) { return value(); }
};

template<>
struct DataType< ::astra_camera::SetLaser > {
  static const char* value()
  {
    return "astra_camera/SetLaser";
  }

  static const char* value(const ::astra_camera::SetLaser&) { return value(); }
};


// service_traits::MD5Sum< ::astra_camera::SetLaserRequest> should match
// service_traits::MD5Sum< ::astra_camera::SetLaser >
template<>
struct MD5Sum< ::astra_camera::SetLaserRequest>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::SetLaser >::value();
  }
  static const char* value(const ::astra_camera::SetLaserRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::SetLaserRequest> should match
// service_traits::DataType< ::astra_camera::SetLaser >
template<>
struct DataType< ::astra_camera::SetLaserRequest>
{
  static const char* value()
  {
    return DataType< ::astra_camera::SetLaser >::value();
  }
  static const char* value(const ::astra_camera::SetLaserRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::astra_camera::SetLaserResponse> should match
// service_traits::MD5Sum< ::astra_camera::SetLaser >
template<>
struct MD5Sum< ::astra_camera::SetLaserResponse>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::SetLaser >::value();
  }
  static const char* value(const ::astra_camera::SetLaserResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::SetLaserResponse> should match
// service_traits::DataType< ::astra_camera::SetLaser >
template<>
struct DataType< ::astra_camera::SetLaserResponse>
{
  static const char* value()
  {
    return DataType< ::astra_camera::SetLaser >::value();
  }
  static const char* value(const ::astra_camera::SetLaserResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASTRA_CAMERA_MESSAGE_SETLASER_H
