// Generated by gencpp from file astra_camera/SetLDP.msg
// DO NOT EDIT!


#ifndef ASTRA_CAMERA_MESSAGE_SETLDP_H
#define ASTRA_CAMERA_MESSAGE_SETLDP_H

#include <ros/service_traits.h>


#include <astra_camera/SetLDPRequest.h>
#include <astra_camera/SetLDPResponse.h>


namespace astra_camera
{

struct SetLDP
{

typedef SetLDPRequest Request;
typedef SetLDPResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLDP
} // namespace astra_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::astra_camera::SetLDP > {
  static const char* value()
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const ::astra_camera::SetLDP&) { return value(); }
};

template<>
struct DataType< ::astra_camera::SetLDP > {
  static const char* value()
  {
    return "astra_camera/SetLDP";
  }

  static const char* value(const ::astra_camera::SetLDP&) { return value(); }
};


// service_traits::MD5Sum< ::astra_camera::SetLDPRequest> should match
// service_traits::MD5Sum< ::astra_camera::SetLDP >
template<>
struct MD5Sum< ::astra_camera::SetLDPRequest>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::SetLDP >::value();
  }
  static const char* value(const ::astra_camera::SetLDPRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::SetLDPRequest> should match
// service_traits::DataType< ::astra_camera::SetLDP >
template<>
struct DataType< ::astra_camera::SetLDPRequest>
{
  static const char* value()
  {
    return DataType< ::astra_camera::SetLDP >::value();
  }
  static const char* value(const ::astra_camera::SetLDPRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::astra_camera::SetLDPResponse> should match
// service_traits::MD5Sum< ::astra_camera::SetLDP >
template<>
struct MD5Sum< ::astra_camera::SetLDPResponse>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::SetLDP >::value();
  }
  static const char* value(const ::astra_camera::SetLDPResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::SetLDPResponse> should match
// service_traits::DataType< ::astra_camera::SetLDP >
template<>
struct DataType< ::astra_camera::SetLDPResponse>
{
  static const char* value()
  {
    return DataType< ::astra_camera::SetLDP >::value();
  }
  static const char* value(const ::astra_camera::SetLDPResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASTRA_CAMERA_MESSAGE_SETLDP_H
