// Generated by gencpp from file world_canvas_msgs/EditAnnotationsData.msg
// DO NOT EDIT!


#ifndef WORLD_CANVAS_MSGS_MESSAGE_EDITANNOTATIONSDATA_H
#define WORLD_CANVAS_MSGS_MESSAGE_EDITANNOTATIONSDATA_H

#include <ros/service_traits.h>


#include <world_canvas_msgs/EditAnnotationsDataRequest.h>
#include <world_canvas_msgs/EditAnnotationsDataResponse.h>


namespace world_canvas_msgs
{

struct EditAnnotationsData
{

typedef EditAnnotationsDataRequest Request;
typedef EditAnnotationsDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EditAnnotationsData
} // namespace world_canvas_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::world_canvas_msgs::EditAnnotationsData > {
  static const char* value()
  {
    return "457c97e1836c61682d0f4bb2f4defba9";
  }

  static const char* value(const ::world_canvas_msgs::EditAnnotationsData&) { return value(); }
};

template<>
struct DataType< ::world_canvas_msgs::EditAnnotationsData > {
  static const char* value()
  {
    return "world_canvas_msgs/EditAnnotationsData";
  }

  static const char* value(const ::world_canvas_msgs::EditAnnotationsData&) { return value(); }
};


// service_traits::MD5Sum< ::world_canvas_msgs::EditAnnotationsDataRequest> should match
// service_traits::MD5Sum< ::world_canvas_msgs::EditAnnotationsData >
template<>
struct MD5Sum< ::world_canvas_msgs::EditAnnotationsDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::world_canvas_msgs::EditAnnotationsData >::value();
  }
  static const char* value(const ::world_canvas_msgs::EditAnnotationsDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_canvas_msgs::EditAnnotationsDataRequest> should match
// service_traits::DataType< ::world_canvas_msgs::EditAnnotationsData >
template<>
struct DataType< ::world_canvas_msgs::EditAnnotationsDataRequest>
{
  static const char* value()
  {
    return DataType< ::world_canvas_msgs::EditAnnotationsData >::value();
  }
  static const char* value(const ::world_canvas_msgs::EditAnnotationsDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::world_canvas_msgs::EditAnnotationsDataResponse> should match
// service_traits::MD5Sum< ::world_canvas_msgs::EditAnnotationsData >
template<>
struct MD5Sum< ::world_canvas_msgs::EditAnnotationsDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::world_canvas_msgs::EditAnnotationsData >::value();
  }
  static const char* value(const ::world_canvas_msgs::EditAnnotationsDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_canvas_msgs::EditAnnotationsDataResponse> should match
// service_traits::DataType< ::world_canvas_msgs::EditAnnotationsData >
template<>
struct DataType< ::world_canvas_msgs::EditAnnotationsDataResponse>
{
  static const char* value()
  {
    return DataType< ::world_canvas_msgs::EditAnnotationsData >::value();
  }
  static const char* value(const ::world_canvas_msgs::EditAnnotationsDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WORLD_CANVAS_MSGS_MESSAGE_EDITANNOTATIONSDATA_H
