// Generated by gencpp from file world_canvas_msgs/GetAnnotationsData.msg
// DO NOT EDIT!


#ifndef WORLD_CANVAS_MSGS_MESSAGE_GETANNOTATIONSDATA_H
#define WORLD_CANVAS_MSGS_MESSAGE_GETANNOTATIONSDATA_H

#include <ros/service_traits.h>


#include <world_canvas_msgs/GetAnnotationsDataRequest.h>
#include <world_canvas_msgs/GetAnnotationsDataResponse.h>


namespace world_canvas_msgs
{

struct GetAnnotationsData
{

typedef GetAnnotationsDataRequest Request;
typedef GetAnnotationsDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAnnotationsData
} // namespace world_canvas_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::world_canvas_msgs::GetAnnotationsData > {
  static const char* value()
  {
    return "91d9a7f0b1315b44e207eeb7e9326135";
  }

  static const char* value(const ::world_canvas_msgs::GetAnnotationsData&) { return value(); }
};

template<>
struct DataType< ::world_canvas_msgs::GetAnnotationsData > {
  static const char* value()
  {
    return "world_canvas_msgs/GetAnnotationsData";
  }

  static const char* value(const ::world_canvas_msgs::GetAnnotationsData&) { return value(); }
};


// service_traits::MD5Sum< ::world_canvas_msgs::GetAnnotationsDataRequest> should match
// service_traits::MD5Sum< ::world_canvas_msgs::GetAnnotationsData >
template<>
struct MD5Sum< ::world_canvas_msgs::GetAnnotationsDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::world_canvas_msgs::GetAnnotationsData >::value();
  }
  static const char* value(const ::world_canvas_msgs::GetAnnotationsDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_canvas_msgs::GetAnnotationsDataRequest> should match
// service_traits::DataType< ::world_canvas_msgs::GetAnnotationsData >
template<>
struct DataType< ::world_canvas_msgs::GetAnnotationsDataRequest>
{
  static const char* value()
  {
    return DataType< ::world_canvas_msgs::GetAnnotationsData >::value();
  }
  static const char* value(const ::world_canvas_msgs::GetAnnotationsDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::world_canvas_msgs::GetAnnotationsDataResponse> should match
// service_traits::MD5Sum< ::world_canvas_msgs::GetAnnotationsData >
template<>
struct MD5Sum< ::world_canvas_msgs::GetAnnotationsDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::world_canvas_msgs::GetAnnotationsData >::value();
  }
  static const char* value(const ::world_canvas_msgs::GetAnnotationsDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_canvas_msgs::GetAnnotationsDataResponse> should match
// service_traits::DataType< ::world_canvas_msgs::GetAnnotationsData >
template<>
struct DataType< ::world_canvas_msgs::GetAnnotationsDataResponse>
{
  static const char* value()
  {
    return DataType< ::world_canvas_msgs::GetAnnotationsData >::value();
  }
  static const char* value(const ::world_canvas_msgs::GetAnnotationsDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WORLD_CANVAS_MSGS_MESSAGE_GETANNOTATIONSDATA_H
