// Generated by gencpp from file world_canvas_msgs/ListMaps.msg
// DO NOT EDIT!


#ifndef WORLD_CANVAS_MSGS_MESSAGE_LISTMAPS_H
#define WORLD_CANVAS_MSGS_MESSAGE_LISTMAPS_H

#include <ros/service_traits.h>


#include <world_canvas_msgs/ListMapsRequest.h>
#include <world_canvas_msgs/ListMapsResponse.h>


namespace world_canvas_msgs
{

struct ListMaps
{

typedef ListMapsRequest Request;
typedef ListMapsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListMaps
} // namespace world_canvas_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::world_canvas_msgs::ListMaps > {
  static const char* value()
  {
    return "ca5a33dd106a2c24cfd54c927d214957";
  }

  static const char* value(const ::world_canvas_msgs::ListMaps&) { return value(); }
};

template<>
struct DataType< ::world_canvas_msgs::ListMaps > {
  static const char* value()
  {
    return "world_canvas_msgs/ListMaps";
  }

  static const char* value(const ::world_canvas_msgs::ListMaps&) { return value(); }
};


// service_traits::MD5Sum< ::world_canvas_msgs::ListMapsRequest> should match
// service_traits::MD5Sum< ::world_canvas_msgs::ListMaps >
template<>
struct MD5Sum< ::world_canvas_msgs::ListMapsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::world_canvas_msgs::ListMaps >::value();
  }
  static const char* value(const ::world_canvas_msgs::ListMapsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_canvas_msgs::ListMapsRequest> should match
// service_traits::DataType< ::world_canvas_msgs::ListMaps >
template<>
struct DataType< ::world_canvas_msgs::ListMapsRequest>
{
  static const char* value()
  {
    return DataType< ::world_canvas_msgs::ListMaps >::value();
  }
  static const char* value(const ::world_canvas_msgs::ListMapsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::world_canvas_msgs::ListMapsResponse> should match
// service_traits::MD5Sum< ::world_canvas_msgs::ListMaps >
template<>
struct MD5Sum< ::world_canvas_msgs::ListMapsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::world_canvas_msgs::ListMaps >::value();
  }
  static const char* value(const ::world_canvas_msgs::ListMapsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_canvas_msgs::ListMapsResponse> should match
// service_traits::DataType< ::world_canvas_msgs::ListMaps >
template<>
struct DataType< ::world_canvas_msgs::ListMapsResponse>
{
  static const char* value()
  {
    return DataType< ::world_canvas_msgs::ListMaps >::value();
  }
  static const char* value(const ::world_canvas_msgs::ListMapsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WORLD_CANVAS_MSGS_MESSAGE_LISTMAPS_H
