// Generated by gencpp from file world_canvas_msgs/ListMapsResponse.msg
// DO NOT EDIT!


#ifndef WORLD_CANVAS_MSGS_MESSAGE_LISTMAPSRESPONSE_H
#define WORLD_CANVAS_MSGS_MESSAGE_LISTMAPSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <world_canvas_msgs/MapListEntry.h>

namespace world_canvas_msgs
{
template <class ContainerAllocator>
struct ListMapsResponse_
{
  typedef ListMapsResponse_<ContainerAllocator> Type;

  ListMapsResponse_()
    : map_list()  {
    }
  ListMapsResponse_(const ContainerAllocator& _alloc)
    : map_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::world_canvas_msgs::MapListEntry_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::world_canvas_msgs::MapListEntry_<ContainerAllocator> >::other >  _map_list_type;
  _map_list_type map_list;





  typedef boost::shared_ptr< ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ListMapsResponse_

typedef ::world_canvas_msgs::ListMapsResponse_<std::allocator<void> > ListMapsResponse;

typedef boost::shared_ptr< ::world_canvas_msgs::ListMapsResponse > ListMapsResponsePtr;
typedef boost::shared_ptr< ::world_canvas_msgs::ListMapsResponse const> ListMapsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator1> & lhs, const ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.map_list == rhs.map_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator1> & lhs, const ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace world_canvas_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca5a33dd106a2c24cfd54c927d214957";
  }

  static const char* value(const ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca5a33dd106a2c24ULL;
  static const uint64_t static_value2 = 0xcfd54c927d214957ULL;
};

template<class ContainerAllocator>
struct DataType< ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "world_canvas_msgs/ListMapsResponse";
  }

  static const char* value(const ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MapListEntry[] map_list\n"
"\n"
"\n"
"================================================================================\n"
"MSG: world_canvas_msgs/MapListEntry\n"
"# One entry in a list of maps.\n"
"\n"
"# Naming a map is optional.\n"
"string name\n"
"\n"
"# Maps made by the make-a-map app are given a session ID, which is the\n"
"# time when the map-making session was started, expressed as seconds\n"
"# since the epoch and converted to a string.\n"
"string session_id\n"
"\n"
"# Creation time of this map, in seconds since the epoch.\n"
"int64 date\n"
"\n"
"# Unique ID of this map.\n"
"string map_id\n"
;
  }

  static const char* value(const ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListMapsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::world_canvas_msgs::ListMapsResponse_<ContainerAllocator>& v)
  {
    s << indent << "map_list[]" << std::endl;
    for (size_t i = 0; i < v.map_list.size(); ++i)
    {
      s << indent << "  map_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::world_canvas_msgs::MapListEntry_<ContainerAllocator> >::stream(s, indent + "    ", v.map_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORLD_CANVAS_MSGS_MESSAGE_LISTMAPSRESPONSE_H
