// Generated by gencpp from file world_canvas_msgs/SaveMap.msg
// DO NOT EDIT!


#ifndef WORLD_CANVAS_MSGS_MESSAGE_SAVEMAP_H
#define WORLD_CANVAS_MSGS_MESSAGE_SAVEMAP_H

#include <ros/service_traits.h>


#include <world_canvas_msgs/SaveMapRequest.h>
#include <world_canvas_msgs/SaveMapResponse.h>


namespace world_canvas_msgs
{

struct SaveMap
{

typedef SaveMapRequest Request;
typedef SaveMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveMap
} // namespace world_canvas_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::world_canvas_msgs::SaveMap > {
  static const char* value()
  {
    return "25e928a2d4ff388c294895b7af935978";
  }

  static const char* value(const ::world_canvas_msgs::SaveMap&) { return value(); }
};

template<>
struct DataType< ::world_canvas_msgs::SaveMap > {
  static const char* value()
  {
    return "world_canvas_msgs/SaveMap";
  }

  static const char* value(const ::world_canvas_msgs::SaveMap&) { return value(); }
};


// service_traits::MD5Sum< ::world_canvas_msgs::SaveMapRequest> should match
// service_traits::MD5Sum< ::world_canvas_msgs::SaveMap >
template<>
struct MD5Sum< ::world_canvas_msgs::SaveMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::world_canvas_msgs::SaveMap >::value();
  }
  static const char* value(const ::world_canvas_msgs::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_canvas_msgs::SaveMapRequest> should match
// service_traits::DataType< ::world_canvas_msgs::SaveMap >
template<>
struct DataType< ::world_canvas_msgs::SaveMapRequest>
{
  static const char* value()
  {
    return DataType< ::world_canvas_msgs::SaveMap >::value();
  }
  static const char* value(const ::world_canvas_msgs::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::world_canvas_msgs::SaveMapResponse> should match
// service_traits::MD5Sum< ::world_canvas_msgs::SaveMap >
template<>
struct MD5Sum< ::world_canvas_msgs::SaveMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::world_canvas_msgs::SaveMap >::value();
  }
  static const char* value(const ::world_canvas_msgs::SaveMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_canvas_msgs::SaveMapResponse> should match
// service_traits::DataType< ::world_canvas_msgs::SaveMap >
template<>
struct DataType< ::world_canvas_msgs::SaveMapResponse>
{
  static const char* value()
  {
    return DataType< ::world_canvas_msgs::SaveMap >::value();
  }
  static const char* value(const ::world_canvas_msgs::SaveMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WORLD_CANVAS_MSGS_MESSAGE_SAVEMAP_H
