// Generated by gencpp from file world_canvas_msgs/SetRelationshipRequest.msg
// DO NOT EDIT!


#ifndef WORLD_CANVAS_MSGS_MESSAGE_SETRELATIONSHIPREQUEST_H
#define WORLD_CANVAS_MSGS_MESSAGE_SETRELATIONSHIPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <uuid_msgs/UniqueID.h>
#include <uuid_msgs/UniqueID.h>

namespace world_canvas_msgs
{
template <class ContainerAllocator>
struct SetRelationshipRequest_
{
  typedef SetRelationshipRequest_<ContainerAllocator> Type;

  SetRelationshipRequest_()
    : id()
    , relationship()
    , action(0)  {
    }
  SetRelationshipRequest_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , relationship(_alloc)
    , action(0)  {
  (void)_alloc;
    }



   typedef  ::uuid_msgs::UniqueID_<ContainerAllocator>  _id_type;
  _id_type id;

   typedef  ::uuid_msgs::UniqueID_<ContainerAllocator>  _relationship_type;
  _relationship_type relationship;

   typedef uint8_t _action_type;
  _action_type action;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ADD)
  #undef ADD
#endif
#if defined(_WIN32) && defined(DEL)
  #undef DEL
#endif

  enum {
    ADD = 1u,
    DEL = 2u,
  };


  typedef boost::shared_ptr< ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRelationshipRequest_

typedef ::world_canvas_msgs::SetRelationshipRequest_<std::allocator<void> > SetRelationshipRequest;

typedef boost::shared_ptr< ::world_canvas_msgs::SetRelationshipRequest > SetRelationshipRequestPtr;
typedef boost::shared_ptr< ::world_canvas_msgs::SetRelationshipRequest const> SetRelationshipRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator1> & lhs, const ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.relationship == rhs.relationship &&
    lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator1> & lhs, const ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace world_canvas_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "959a407bfae0a7caca19dd67a720b2b8";
  }

  static const char* value(const ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x959a407bfae0a7caULL;
  static const uint64_t static_value2 = 0xca19dd67a720b2b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "world_canvas_msgs/SetRelationshipRequest";
  }

  static const char* value(const ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Add/remove a specific relationship to the specified annotation\n"
"uint8 ADD = 1\n"
"uint8 DEL = 2\n"
"\n"
"uuid_msgs/UniqueID id\n"
"uuid_msgs/UniqueID relationship\n"
"uint8 action\n"
"\n"
"================================================================================\n"
"MSG: uuid_msgs/UniqueID\n"
"# A universally unique identifier (UUID).\n"
"#\n"
"#  http://en.wikipedia.org/wiki/Universally_unique_identifier\n"
"#  http://tools.ietf.org/html/rfc4122.html\n"
"\n"
"uint8[16] uuid\n"
;
  }

  static const char* value(const ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.relationship);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRelationshipRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::world_canvas_msgs::SetRelationshipRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    s << std::endl;
    Printer< ::uuid_msgs::UniqueID_<ContainerAllocator> >::stream(s, indent + "  ", v.id);
    s << indent << "relationship: ";
    s << std::endl;
    Printer< ::uuid_msgs::UniqueID_<ContainerAllocator> >::stream(s, indent + "  ", v.relationship);
    s << indent << "action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORLD_CANVAS_MSGS_MESSAGE_SETRELATIONSHIPREQUEST_H
