// Generated by gencpp from file world_canvas_msgs/SetRelationship.msg
// DO NOT EDIT!


#ifndef WORLD_CANVAS_MSGS_MESSAGE_SETRELATIONSHIP_H
#define WORLD_CANVAS_MSGS_MESSAGE_SETRELATIONSHIP_H

#include <ros/service_traits.h>


#include <world_canvas_msgs/SetRelationshipRequest.h>
#include <world_canvas_msgs/SetRelationshipResponse.h>


namespace world_canvas_msgs
{

struct SetRelationship
{

typedef SetRelationshipRequest Request;
typedef SetRelationshipResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRelationship
} // namespace world_canvas_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::world_canvas_msgs::SetRelationship > {
  static const char* value()
  {
    return "c1d8b7af22a1ce2dc6c177d3ab941e79";
  }

  static const char* value(const ::world_canvas_msgs::SetRelationship&) { return value(); }
};

template<>
struct DataType< ::world_canvas_msgs::SetRelationship > {
  static const char* value()
  {
    return "world_canvas_msgs/SetRelationship";
  }

  static const char* value(const ::world_canvas_msgs::SetRelationship&) { return value(); }
};


// service_traits::MD5Sum< ::world_canvas_msgs::SetRelationshipRequest> should match
// service_traits::MD5Sum< ::world_canvas_msgs::SetRelationship >
template<>
struct MD5Sum< ::world_canvas_msgs::SetRelationshipRequest>
{
  static const char* value()
  {
    return MD5Sum< ::world_canvas_msgs::SetRelationship >::value();
  }
  static const char* value(const ::world_canvas_msgs::SetRelationshipRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_canvas_msgs::SetRelationshipRequest> should match
// service_traits::DataType< ::world_canvas_msgs::SetRelationship >
template<>
struct DataType< ::world_canvas_msgs::SetRelationshipRequest>
{
  static const char* value()
  {
    return DataType< ::world_canvas_msgs::SetRelationship >::value();
  }
  static const char* value(const ::world_canvas_msgs::SetRelationshipRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::world_canvas_msgs::SetRelationshipResponse> should match
// service_traits::MD5Sum< ::world_canvas_msgs::SetRelationship >
template<>
struct MD5Sum< ::world_canvas_msgs::SetRelationshipResponse>
{
  static const char* value()
  {
    return MD5Sum< ::world_canvas_msgs::SetRelationship >::value();
  }
  static const char* value(const ::world_canvas_msgs::SetRelationshipResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_canvas_msgs::SetRelationshipResponse> should match
// service_traits::DataType< ::world_canvas_msgs::SetRelationship >
template<>
struct DataType< ::world_canvas_msgs::SetRelationshipResponse>
{
  static const char* value()
  {
    return DataType< ::world_canvas_msgs::SetRelationship >::value();
  }
  static const char* value(const ::world_canvas_msgs::SetRelationshipResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WORLD_CANVAS_MSGS_MESSAGE_SETRELATIONSHIP_H
