// Generated by gencpp from file world_canvas_msgs/YAMLExport.msg
// DO NOT EDIT!


#ifndef WORLD_CANVAS_MSGS_MESSAGE_YAMLEXPORT_H
#define WORLD_CANVAS_MSGS_MESSAGE_YAMLEXPORT_H

#include <ros/service_traits.h>


#include <world_canvas_msgs/YAMLExportRequest.h>
#include <world_canvas_msgs/YAMLExportResponse.h>


namespace world_canvas_msgs
{

struct YAMLExport
{

typedef YAMLExportRequest Request;
typedef YAMLExportResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct YAMLExport
} // namespace world_canvas_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::world_canvas_msgs::YAMLExport > {
  static const char* value()
  {
    return "dea35f0126973fed4bc2a85823db7aa5";
  }

  static const char* value(const ::world_canvas_msgs::YAMLExport&) { return value(); }
};

template<>
struct DataType< ::world_canvas_msgs::YAMLExport > {
  static const char* value()
  {
    return "world_canvas_msgs/YAMLExport";
  }

  static const char* value(const ::world_canvas_msgs::YAMLExport&) { return value(); }
};


// service_traits::MD5Sum< ::world_canvas_msgs::YAMLExportRequest> should match
// service_traits::MD5Sum< ::world_canvas_msgs::YAMLExport >
template<>
struct MD5Sum< ::world_canvas_msgs::YAMLExportRequest>
{
  static const char* value()
  {
    return MD5Sum< ::world_canvas_msgs::YAMLExport >::value();
  }
  static const char* value(const ::world_canvas_msgs::YAMLExportRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_canvas_msgs::YAMLExportRequest> should match
// service_traits::DataType< ::world_canvas_msgs::YAMLExport >
template<>
struct DataType< ::world_canvas_msgs::YAMLExportRequest>
{
  static const char* value()
  {
    return DataType< ::world_canvas_msgs::YAMLExport >::value();
  }
  static const char* value(const ::world_canvas_msgs::YAMLExportRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::world_canvas_msgs::YAMLExportResponse> should match
// service_traits::MD5Sum< ::world_canvas_msgs::YAMLExport >
template<>
struct MD5Sum< ::world_canvas_msgs::YAMLExportResponse>
{
  static const char* value()
  {
    return MD5Sum< ::world_canvas_msgs::YAMLExport >::value();
  }
  static const char* value(const ::world_canvas_msgs::YAMLExportResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_canvas_msgs::YAMLExportResponse> should match
// service_traits::DataType< ::world_canvas_msgs::YAMLExport >
template<>
struct DataType< ::world_canvas_msgs::YAMLExportResponse>
{
  static const char* value()
  {
    return DataType< ::world_canvas_msgs::YAMLExport >::value();
  }
  static const char* value(const ::world_canvas_msgs::YAMLExportResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WORLD_CANVAS_MSGS_MESSAGE_YAMLEXPORT_H
