// Generated by gencpp from file exploration_msgs/ExploreFeedback.msg
// DO NOT EDIT!


#ifndef EXPLORATION_MSGS_MESSAGE_EXPLOREFEEDBACK_H
#define EXPLORATION_MSGS_MESSAGE_EXPLOREFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace exploration_msgs
{
template <class ContainerAllocator>
struct ExploreFeedback_
{
  typedef ExploreFeedback_<ContainerAllocator> Type;

  ExploreFeedback_()
    : current_goal()
    , robot_pose()  {
    }
  ExploreFeedback_(const ContainerAllocator& _alloc)
    : current_goal(_alloc)
    , robot_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _current_goal_type;
  _current_goal_type current_goal;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _robot_pose_type;
  _robot_pose_type robot_pose;





  typedef boost::shared_ptr< ::exploration_msgs::ExploreFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exploration_msgs::ExploreFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ExploreFeedback_

typedef ::exploration_msgs::ExploreFeedback_<std::allocator<void> > ExploreFeedback;

typedef boost::shared_ptr< ::exploration_msgs::ExploreFeedback > ExploreFeedbackPtr;
typedef boost::shared_ptr< ::exploration_msgs::ExploreFeedback const> ExploreFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exploration_msgs::ExploreFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exploration_msgs::ExploreFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exploration_msgs::ExploreFeedback_<ContainerAllocator1> & lhs, const ::exploration_msgs::ExploreFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_goal == rhs.current_goal &&
    lhs.robot_pose == rhs.robot_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exploration_msgs::ExploreFeedback_<ContainerAllocator1> & lhs, const ::exploration_msgs::ExploreFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exploration_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::exploration_msgs::ExploreFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exploration_msgs::ExploreFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration_msgs::ExploreFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration_msgs::ExploreFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration_msgs::ExploreFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration_msgs::ExploreFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exploration_msgs::ExploreFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04fd07ac30b349303a11fb671faa55e1";
  }

  static const char* value(const ::exploration_msgs::ExploreFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04fd07ac30b34930ULL;
  static const uint64_t static_value2 = 0x3a11fb671faa55e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::exploration_msgs::ExploreFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exploration_msgs/ExploreFeedback";
  }

  static const char* value(const ::exploration_msgs::ExploreFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exploration_msgs::ExploreFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"# Current movement goal for exploration\n"
"geometry_msgs/PoseStamped current_goal\n"
"\n"
"# Current robot pose\n"
"geometry_msgs/PoseStamped robot_pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::exploration_msgs::ExploreFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exploration_msgs::ExploreFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_goal);
      stream.next(m.robot_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExploreFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exploration_msgs::ExploreFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exploration_msgs::ExploreFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.current_goal);
    s << indent << "robot_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORATION_MSGS_MESSAGE_EXPLOREFEEDBACK_H
