// Generated by gencpp from file exploration_msgs/SetPolygon.msg
// DO NOT EDIT!


#ifndef EXPLORATION_MSGS_MESSAGE_SETPOLYGON_H
#define EXPLORATION_MSGS_MESSAGE_SETPOLYGON_H

#include <ros/service_traits.h>


#include <exploration_msgs/SetPolygonRequest.h>
#include <exploration_msgs/SetPolygonResponse.h>


namespace exploration_msgs
{

struct SetPolygon
{

typedef SetPolygonRequest Request;
typedef SetPolygonResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPolygon
} // namespace exploration_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exploration_msgs::SetPolygon > {
  static const char* value()
  {
    return "e257093c51f646bb3fd81ee37f162324";
  }

  static const char* value(const ::exploration_msgs::SetPolygon&) { return value(); }
};

template<>
struct DataType< ::exploration_msgs::SetPolygon > {
  static const char* value()
  {
    return "exploration_msgs/SetPolygon";
  }

  static const char* value(const ::exploration_msgs::SetPolygon&) { return value(); }
};


// service_traits::MD5Sum< ::exploration_msgs::SetPolygonRequest> should match
// service_traits::MD5Sum< ::exploration_msgs::SetPolygon >
template<>
struct MD5Sum< ::exploration_msgs::SetPolygonRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exploration_msgs::SetPolygon >::value();
  }
  static const char* value(const ::exploration_msgs::SetPolygonRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exploration_msgs::SetPolygonRequest> should match
// service_traits::DataType< ::exploration_msgs::SetPolygon >
template<>
struct DataType< ::exploration_msgs::SetPolygonRequest>
{
  static const char* value()
  {
    return DataType< ::exploration_msgs::SetPolygon >::value();
  }
  static const char* value(const ::exploration_msgs::SetPolygonRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exploration_msgs::SetPolygonResponse> should match
// service_traits::MD5Sum< ::exploration_msgs::SetPolygon >
template<>
struct MD5Sum< ::exploration_msgs::SetPolygonResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exploration_msgs::SetPolygon >::value();
  }
  static const char* value(const ::exploration_msgs::SetPolygonResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exploration_msgs::SetPolygonResponse> should match
// service_traits::DataType< ::exploration_msgs::SetPolygon >
template<>
struct DataType< ::exploration_msgs::SetPolygonResponse>
{
  static const char* value()
  {
    return DataType< ::exploration_msgs::SetPolygon >::value();
  }
  static const char* value(const ::exploration_msgs::SetPolygonResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXPLORATION_MSGS_MESSAGE_SETPOLYGON_H
